# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de987b06d67a57d70e4b55c94faf0bc50f563d5c5d89ca872550e774a00fa562759c1f92c2079b3aa08f68e9a78cd54a09523cbfed756fd862c13b8d7462463c

test:
  secret_key_base: 2067d2e3cd1431772e3ae0b432db70d003d897de0effc9dc3f73a896fbc56516890e05da305ae48d3bf02482dc9aaacd3b33aecfd02072037880c2814b571cba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
